---

x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

services:
  twitch:
    image: ${C_REGISTRY_BASE:?err}/twitch:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PY_VER: 3.9
    container_name: twitch
    network_mode: "bridge"
    environment:
      <<: *default-env
      BUSY_FILE: "/data/busy"
      ENC_ARGS: '--copy_pattern (by\s*the\s*numbers|no\s*major\W?s\s*club|i\s*hate\s*it\s*here) --copy_pattern_opt IGNORECASE --enable_cleaner'
      ENC_LISTEN_ADDRESS: "127.0.0.1:3626"
      ENC_OUT: ${C_MEDIA}/twitch
      ENC_PATH: "http://127.0.0.1:3626"
      ENC_SRC: /downloads
      GEN_DST: ${C_WEB_ROOT}/clips
      GEN_PG_URI: "uuid_gen:${PG_PASS:?err}@${C_PG_HOST:?err}/web"
      GEN_SRC1: "[clips]${C_MEDIA}/clips"
      GEN_SRC2: "[rl]${C_MEDIA}/twitch/RichardLewisReports"
      # GLOBAL_ARGS: "--no_notifications"
      REC_OUT: /downloads
      REC_TIMEOUT: "120"
      REC_TWITCH_ID: ${TWITCH_ID:?err}
      REC_USER: RichardLewisReports
#      START_GEN: "0"
      WEBHOOK_URL: ${TWITCH_WEBHOOK:?err}
    volumes:
      - ./src:/app
      - ./data:/data
      - ${C_DOWNLOADS:?err}/twitch:/downloads
      - ${C_MEDIA:?err}/twitch:${C_MEDIA}/twitch
      - ${C_MEDIA}/clips:${C_MEDIA}/clips:ro
      - ${C_WEB_ROOT:?err}/clips:${C_WEB_ROOT}/clips
    restart: "always"
