---

default:
  image: docker:29
  tags:
    - docker-socket

  before_script:
    - apk add git
    - git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_USER}".insteadOf "git@github.com:${GITHUB_USER}"
    - docker info
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - env | grep --color=never -E '^C\_'

variables:
  GIT_SUBMODULE_STRATEGY: "none"
  C_REGISTRY_BASE: "$CI_REGISTRY_IMAGE"
  C_TZ: "Europe/Oslo"
  C_UID: "1000"
  C_GID: "1000"
  C_PG_HOST: "dummy"
  C_DOMAIN: "dummy"

stages:
  - build

build:mrbot-web:
  stage: build
  variables:
    PG_PASS: "dummy"
    C_WEB_TAG: "latest"
  script:
    - cd mrbot
    - docker compose build --pull web
    - docker compose push web
    - |
      docker tag "${C_REGISTRY_BASE}/mrbot-web:${C_WEB_TAG}" "${C_REGISTRY_BASE}/mrbot-web:${CI_COMMIT_SHORT_SHA}"
      docker push "${C_REGISTRY_BASE}/mrbot-web:${CI_COMMIT_SHORT_SHA}"
      tag="$(git tag --points-at HEAD | tail -n1)"
      if [ -n "$tag" ]; then
        docker tag "${C_REGISTRY_BASE}/mrbot-web:${C_WEB_TAG}" "${C_REGISTRY_BASE}/mrbot-web:${tag}"
        docker push "${C_REGISTRY_BASE}/mrbot-web:${tag}"
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - changes:
      - '.gitlab-ci.yml'
      - 'mrbot/docker-compose.yml'
      - 'mrbot/nginx'
