containers["jellyfin"]=""
containers["mrbot"]=""
containers["syncthing"]=""
containers["factorio"]=""
containers["prometheus"]=""
containers["portainer"]=""
containers["plex"]=""
containers["vpn"]="vpn sonarr prowlarr"
