---

x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

services:
  dv:
    image: joshava/cloudflare-ddns:latest
    network_mode: "host"
    container_name: ddns-dv
    environment: *default-env
    volumes:
      - ./data/config-dv.yaml:/app/config.yaml
    restart: "always"
