version: "3.7"

services:
  bitwarden:
    image: bitwardenrs/server
    container_name: bitwarden
    network_mode: "bridge"
    user: ${C_UID}:${G_UID}
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN:?err}
      DOMAIN: "https://bw.${C_DOMAIN}/"
      EXTENDED_LOGGING: "true"
      LOG_FILE: /data/bitwarden.log
      LOG_LEVEL: warn
      ROCKET_CLI_COLORS: "off"
      ROCKET_PORT: "8343"
      SIGNUPS_ALLOWED: "true"
      SMTP_FROM: ${SMTP_FROM:?err}
      SMTP_HOST: ${SMTP_HOST:?err}
      SMTP_PASSWORD: ${SMTP_PASSWORD:?err}
      SMTP_PORT: ${SMTP_PORT:?err}
      SMTP_SSL: "true"
      SMTP_USERNAME: ${SMTP_USERNAME:?err}
      TZ: ${C_TZ}
      WEBSOCKET_ENABLED: "true"
    ports:
      - "${C_PORT_BIND_ADDRESS:-0.0.0.0}:8343:8343/tcp"
      - "${C_PORT_BIND_ADDRESS:-0.0.0.0}:3012:3012/tcp"
    volumes:
      - ./data:/data
    restart: "always"
