#!/usr/bin/with-contenv bash

cd /app || exit

# Remove GEN_ prefix and unset GEN_ vars
for var in "${!GEN_@}"; do
    new_var="${var#GEN_}"
    echo "Setting $new_var=\"${!var}\""
    export "$new_var"="${!var}"
    unset "$var"
done

exec s6-setuidgid abc python launcher.py uuid
