#!/usr/bin/with-contenv bash

cd /app || exit

# Remove ENC_ prefix and unset ENC_ vars
for var in "${!ENC_@}"; do
    new_var="${var#ENC_}"
    echo "Setting $new_var=\"${!var}\""
    export "$new_var"="${!var}"
    unset "$var"
done

exec s6-setuidgid abc python launcher.py encoder
