---

version: "3.7"

services:
  plex:
    extends:
      file: base.yml
      service: plex
    volumes:
      - ./data/transcode:/transcode
      - /mnt/user/video:/media/video
      - /mnt/user/photo:/media/photo
      - /mnt/user/archive/Music:/media/music
    network_mode: host
