version: '3'

x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

services:
  satisfactory:
    container_name: 'satisfactory'
    hostname: 'satisfactory'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '${C_PORT_BIND_ADDRESS:-0.0.0.0}:7777:7777/udp'   # Game
      - '${C_PORT_BIND_ADDRESS:-0.0.0.0}:15000:15000/udp' # Beacon
      - '${C_PORT_BIND_ADDRESS:-0.0.0.0}:15777:15777/udp' # Query
    volumes:
      - './data:/config'
    environment:
      <<: *default-env
      - MAXPLAYERS=2
      - STEAMBETA=false
    restart: unless-stopped
    stop_grace_period: 1m
    security_opt:
      - label=disable
    logging:
      driver: k8s-file
      options:
        path: /var/log/podman/satisfactory.log
        max-size: 10mb
    deploy:
      resources:
        limits:
          memory: 24G
        reservations:
          memory: 12G
