---

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          instance: "{{ prometheus_self_name }}"
          am_missing: "ignore"

  - job_name: 'docker-swarm'
    dockerswarm_sd_configs:
      - host: unix:///run/docker.sock
        role: tasks
    relabel_configs:
      # Only keep containers that should be running.
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_network_name]
        regex: monitoring
        action: keep
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        regex: .+
        action: keep
      # Use the prometheus-job Swarm label as Prometheus job label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        target_label: job
      # Replace instance with service name
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: instance
      # Add docker node label
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: docker_node
      # Use the task labels that are prefixed by `prometheus-`.
      - regex: __meta_dockerswarm_service_label_prometheus_(.+)
        action: labelmap
        replacement: $1
