---

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          instance: "{{ prometheus_self_name }}"
          am_missing: "ignore"

  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///run/docker.sock
    relabel_configs:
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: .+
        action: keep
      # Only scrape containers in the monitoring network
      - source_labels: [__meta_docker_network_name]
        regex: monitoring
        action: keep
      # Replace instance with value from label
      - source_labels: [__meta_docker_container_label_prometheus_instance]
        target_label: instance
        regex: .+
        replacement: $1
      # Use the task labels that are prefixed by `prometheus-`.
      - regex: __meta_docker_container_label_prometheus_(.+)
        action: labelmap
        replacement: $1
