---

services:
  vouch:
    image: voucher/vouch-proxy:latest
    network_mode: "host"
    container_name: vouch
    user: ${C_UID}:${C_GID}
    environment:
      TZ: ${C_TZ}
    volumes:
      - ./data/config.yaml:/config/config.yaml
    restart: "always"
