version: "3.7"

x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

services:
  tfbuild-gpu:
    image: ${C_REGISTRY_BASE:?err}/tfbuild:gpu
    build:
      context: .
      dockerfile: gpu1.Dockerfile
      args:
        PY_VER: 3.7
        TF_VERSION: v1.15.4
        # TF_VERSION: v1.14.0
        USE_TF_PIP: 0
    container_name: tfbuild
    network_mode: "bridge"
    stdin_open: true
    tty: true
    environment: *default-env
    volumes:
      - ./data:/data
      - ./files/make-gpu.sh:/src/make.sh
    restart: "no"
