version: "3.7"
x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    network_mode: "bridge"
    container_name: nextcloud
    hostname: cloud.${C_DOMAIN:?err}
    environment: *default-env
    volumes:
      - /run/postgresql:/run/postgresql
      - ./data/data:/data
      - ./data/config:/config
    ports:
      - "127.0.0.1:25683:443"
    restart: "always"
