---

version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: "bridge"
    volumes:
      - ./data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "${C_PORT_BIND_ADDRESS:-0.0.0.0}:8123:8123"
