version: '3'

services:
  # export TOKEN=""
  # docker run --rm -v $PWD/data/runner:/etc/gitlab-runner gitlab/gitlab-runner register \
  #   --non-interactive \
  #   --executor "docker" \
  #   --docker-image alpine:latest \
  #   --url "https://gitlab.${C_DOMAIN}" \
  #   --registration-token "$TOKEN" \
  #   --description "docker-runner" \
  #   --tag-list "docker" \
  #   --run-untagged="true" \
  #   --locked="false" \
  #   --access-level="not_protected"
  runner:
    image: "gitlab/gitlab-runner:latest"
    restart: "always"
    network_mode: "bridge"
    environment:
      TZ: "${C_TZ:-UTC}"
    volumes:
      - "./data/runner:/etc/gitlab-runner"
      - "/run/docker.sock:/var/run/docker.sock"

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.${C_DOMAIN:?err}'
    network_mode: "bridge"
    container_name: gitlab
    environment:
      TZ: "${C_TZ:-UTC}"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.${C_DOMAIN}'
        registry_external_url 'https://registry.${C_DOMAIN}'
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_database'] = 'gitlabhq_production'
        gitlab_rails['db_encoding'] = 'unicode'
        gitlab_rails['db_host'] = '${C_PG_HOST:?err}'
        gitlab_rails['db_password'] = '${POSTGRES_PASSWORD:?err}'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['gitlab_email_display_name'] = 'GitLab'
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'gitlab@${C_DOMAIN}'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@${C_DOMAIN}'
        gitlab_rails['ldap_enabled'] = false
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['smtp_address'] = '${SMTP_HOST:?err}'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_domain'] = '${C_DOMAIN}'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_password'] = '${SMTP_PASSWORD:?err}'
        gitlab_rails['smtp_port'] = '${SMTP_PORT:?err}'
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_user_name'] = '${SMTP_USERNAME:?err}'
        grafana['enable'] = false
        letsencrypt['enable'] =  false
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        nginx['real_ip_header'] = 'X-Forwarded-For'
        nginx['real_ip_recursive'] = 'on'
        nginx['real_ip_trusted_addresses'] = ['${C_HOST_IPV4:?err}']
        node_exporter['enable'] = false
        postgres_exporter['enable'] = false
        postgresql['enable'] = false
        prometheus['enable'] = false
        registry_nginx['listen_https'] = false
        registry_nginx['listen_port'] = 4524
        registry_nginx['real_ip_header'] = 'X-Forwarded-For'
        registry_nginx['real_ip_recursive'] = 'on'
        registry_nginx['real_ip_trusted_addresses'] = ['${C_HOST_IPV4:?err}']
    ports:
      - '127.0.0.1:4522:80'    # Web
      - '0.0.0.0:4523:22'      # SSH
      - '127.0.0.1:5000:4524'  # Registry
    volumes:
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - './data/data:/var/opt/gitlab'
