version: "3.7"
x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

volumes:
  run-brains:

services:
  bot:
    image: ${C_REPO:-cosandr}:mrbot
    build:
      context: .
      dockerfile: bot.Dockerfile
    container_name: mrbot
    network_mode: "bridge"
    environment:
      <<: *default-env
      CONFIG_DSN: ${CONFIG_DSN:?err}
      LAUNCHER_ARGS: "psql-config --env -e docker"
    volumes:
      - /run/postgresql:/run/postgresql
      - run-brains:/run/app
      - ./data:/data
      - ./src:/app
      - ${C_WEB_ROOT}/discord:/upload
    restart: "always"
    depends_on:
      - brains

  brains:
    image: ${C_REPO:-cosandr}:mrbot-brains
    build:
      context: .
      dockerfile: brains.Dockerfile
    container_name: mrbot-brains
    network_mode: "bridge"
    environment:
      <<: *default-env
      DATA_PATH: /data
      UPLOAD_PATH: /upload
      UPLOAD_URL: "https://www.${C_DOMAIN}/discord"
      LISTEN_ADDRESS: "/run/app/brains.sock"
    volumes:
      - run-brains:/run/app
      - ./data:/data
      - ./src-brains:/app
      - ${C_WEB_ROOT}/discord:/upload
    restart: "always"
