---

x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

services:
  factorio:
    hostname: ${C_FACTORIO_NAME:-${C_HOSTNAME:?err}}
    ## Breaks promtail
    # stdin_open: true
    # tty: true
    container_name: factorio
    image: factoriotools/factorio:stable
    ports:
     - "${C_PORT_BIND_ADDRESS:-0.0.0.0}:34197:34197/udp"
#     - "${C_PORT_BIND_ADDRESS:-0.0.0.0}:27015:27015/tcp"
    volumes:
     - ./data:/factorio
     - ./server-settings.json:/server-settings.json
    entrypoint: /bin/sh -c "mkdir -p /factorio/config && envsubst < /server-settings.json > /factorio/config/server-settings.json && exec /docker-entrypoint.sh"
    environment:
      <<: *default-env
      GENERATE_NEW_SAVE: "false"
      LOAD_LATEST_SAVE: "true"
      INSTANCE_NAME: ${INSTANCE_NAME:?err}
      INSTANCE_DESC: ${INSTANCE_DESC:?err}
      INSTANCE_PASSWORD: ${INSTANCE_PASSWORD:?err}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      resources:
        reservations:
          cpus: '1.0'
          memory: '10G'
