version: "3.7"
x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    network_mode: "bridge"
    environment:
      <<: *default-env
      UMASK_SET: 022
    volumes:
      - ./data:/config
      - ${C_MEDIA:?err}:/data/media
      - ${C_MEDIA_YES:?err}:/data/yes
    ports:
      - "${C_PORT_BIND_ADDRESS:-0.0.0.0}:8096:8096/tcp" # HTTP
      # - "${C_PORT_BIND_ADDRESS:-0.0.0.0}:1900:1900/udp" # Auto-discovery
      # - "${C_PORT_BIND_ADDRESS:-0.0.0.0}:7359:7359/udp" # Auto-discovery
    restart: unless-stopped
