version: "3.7"

services:
  opencv-build:
    image: ${C_REGISTRY_BASE:?err}/opencv-build:deb
    build:
      context: .
      dockerfile: deb.Dockerfile
      args:
        PY_VER: 3.8
        MAKE_PIP: "1"
        OPENCV_VERSION: 58 # 4.5.4.58
        CMAKE_VERSION: v3.21.4
    container_name: opencv-build
    network_mode: "bridge"
    stdin_open: true
    tty: true
    environment:
      TZ: ${C_TZ}
      PUID: ${C_UID}
      PGID: ${C_GID}
    volumes:
      - ./data:/data
    restart: "no"
