---

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "${C_PORT_BIND_ADDRESS:-0.0.0.0}:9443:9443"
      - "${C_PORT_BIND_ADDRESS:-0.0.0.0}:8000:8000"
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - ./data:/data
