version: "3.7"

x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

services:
  chromium-build:
    image: ${C_REGISTRY_BASE:?err}/chromium-build:arch
    build:
      context: .
      dockerfile: arch.Dockerfile
    container_name: chromium-build
    network_mode: "bridge"
    stdin_open: true
    tty: true
    environment: *default-env
    volumes:
      - ./data:/data
    restart: "no"
