version: "3.7"
x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    network_mode: "bridge"
    environment: *default-env
    volumes:
      - ./data:/var/syncthing
      - ${C_MEDIA:?err}/photo:/sync/photo
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart: "always"
