---

x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

networks:
  monitoring:
    external: true
  syncthing:
    driver: ${C_NETWORK_DRIVER:-"overlay"}

services:
  syncthing:
    image: syncthing/syncthing:latest
    networks:
      - syncthing
    environment: *default-env
    volumes:
      - ./data:/var/syncthing
      - ${C_MEDIA:?err}/photo:/sync/photo
    ports:
      - "8384:8384/tcp"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"

  syncthing_exporter:
    image: f100024/syncthing_exporter:latest
    networks:
      - syncthing
      - monitoring
    depends_on:
      - syncthing
    ports:
      - target: 9093
        published: 9093
        protocol: tcp
        mode: host
    environment:
      <<: *default-env
      SYNCTHING_URI: "http://syncthing:8384/"
      SYNCTHING_TOKEN: "${SYNCTHING_TOKEN:?err}"
      SYNCTHING_FOLDERSID: "ctkwt-teehm"
    deploy:
      labels:
        - prometheus-job=syncthing
