version: "3.7"
x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

networks:
  mrbot:
    driver: bridge

volumes:
  run-brains:

services:
  bot:
    image: ${C_REGISTRY_BASE:?err}/mrbot:latest
    build:
      context: .
      dockerfile: bot.Dockerfile
      args:
        PY_VER: "3.10"
    container_name: mrbot
    networks:
      - mrbot
    environment:
      <<: *default-env
      BUSY_FILE: "/data/busy"
      CONFIG_DSN: "postgres://discord:${PG_PASS:?err}@${C_PG_HOST:?err}/discord"
      LAUNCHER_ARGS: "psql-config --env -e docker"
    volumes:
      - run-brains:/run/app
      - ./data/web:/upload
      - ./data/bot:/data
      - ./src:/app
    restart: "always"
    depends_on:
      - brains

  brains:
    image: ${C_REGISTRY_BASE:?err}/mrbot-brains:latest
    build:
      context: .
      dockerfile: brains.Dockerfile
      args:
        PY_VER: 3.8
    container_name: mrbot-brains
    networks:
      - mrbot
    environment:
      <<: *default-env
      DATA_PATH: /data
      UPLOAD_PATH: /upload
      UPLOAD_URL: "https://www.${C_DOMAIN:?err}/discord"
      LISTEN_ADDRESS: "/run/app/brains.sock"
    volumes:
      - run-brains:/run/app
      - ./data/web:/upload
      - ./data/bot:/data
      - ./src-brains:/app
    restart: "always"

  web:
    image: ${C_REGISTRY_BASE:?err}/mrbot-web:latest
    build:
      context: nginx
    container_name: mrbot-web
    volumes:
      - ./data/web:/usr/share/nginx/html
    networks:
      - mrbot
    ports:
      - "${C_HOST_IPV4:?err}:8001:80/tcp"
    environment:
      <<: *default-env
      NGINX_PORT: 80
