version: "3.7"
x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

volumes:
  run-brains:

services:
  bot:
    image: ${C_REGISTRY_BASE:?err}/mrbot:latest
    build:
      context: .
      dockerfile: bot.Dockerfile
      args:
        PY_VER: 3.9
    container_name: mrbot
    network_mode: "bridge"
    environment:
      <<: *default-env
      BUSY_FILE: "/data/busy"
      CONFIG_DSN: ${CONFIG_DSN:?err}
      LAUNCHER_ARGS: "psql-config --env -e docker"
    volumes:
      - /run/postgresql:/run/postgresql
      - run-brains:/run/app
      - ./data:/data
      - ./src:/app
      - ${C_WEB_ROOT:?err}/discord:/upload
    restart: "always"
    depends_on:
      - brains

  brains:
    image: ${C_REGISTRY_BASE:?err}/mrbot-brains:latest
    build:
      context: .
      dockerfile: brains.Dockerfile
      args:
        PY_VER: 3.8
    container_name: mrbot-brains
    network_mode: "bridge"
    environment:
      <<: *default-env
      DATA_PATH: /data
      UPLOAD_PATH: /upload
      UPLOAD_URL: "https://www.${C_DOMAIN:?err}/discord"
      LISTEN_ADDRESS: "/run/app/brains.sock"
    volumes:
      - run-brains:/run/app
      - ./data:/data
      - ./src-brains:/app
      - ${C_WEB_ROOT:?err}/discord:/upload
    restart: "always"
