---

x-env: &default-env
  TZ: ${C_TZ}
  PUID: ${C_UID}
  PGID: ${C_GID}

networks:
  mrbot:

services:
  bot:
    image: ${C_REGISTRY_BASE:?err}/mrbot:${C_BOT_TAG:-latest}
    build:
      context: .
      dockerfile: bot.Dockerfile
      args:
        PY_VER: "3.10"
    container_name: mrbot
    networks:
      - mrbot
    environment:
      <<: *default-env
      BUSY_FILE: "/data/busy"
      CONFIG_DSN: "postgres://discord:${PG_PASS:?err}@${C_PG_HOST:?err}/discord"
      LAUNCHER_ARGS: "psql-config --env -e docker"
    volumes:
      - ./data/web:/upload
      - ./data/bot:/data
      - ./src:/app
    restart: "always"
    depends_on:
      - brains

  brains:
    image: ${C_REGISTRY_BASE:?err}/mrbot-brains:${C_BRAINS_TAG:-latest}
    build:
      context: .
      dockerfile: brains.Dockerfile
      args:
        PY_VER: 3.8
    container_name: mrbot-brains
    networks:
      - mrbot
    environment:
      <<: *default-env
      DATA_PATH: /data
      UPLOAD_PATH: /upload
      UPLOAD_URL: "https://www.${C_DOMAIN:?err}/discord"
      LISTEN_ADDRESS: "0.0.0.0:7762"
    volumes:
      - ./data/web:/upload
      - ./data/bot:/data
      - ./src-brains:/app
    restart: "always"

  web:
    image: ${C_REGISTRY_BASE:?err}/mrbot-web:${C_WEB_TAG:-latest}
    build:
      context: nginx
    container_name: mrbot-web
    volumes:
      - ./data/web:/usr/share/nginx/html
    networks:
      - mrbot
    ports:
      - "${C_PORT_BIND_ADDRESS:-0.0.0.0}:8001:80/tcp"
    environment:
      <<: *default-env
      NGINX_PORT: 80
